### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by klev-sm** [klev-sm/countries-api#1]
# TODO
- [x] Getting all countries through api
- [x] Sanitize data from api
- [x] List of countries
- [x] Saving countries data in its own database.
- [x] Count of likes in a country
- [x] Country search filters by name and region
- [ ] Improve the code of json responses

**Comment by matos-ed** [comment]
Suggestions:

- [ ] Saving countries data in its own database. 

The Countries API may have a maximum limit of requests per ip, so the best would be:
- If there are countries saved in the database, return them
- If not, look for it in the api and save it in the database
